language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0
      - python3
      - python3-pip
      - python3-setuptools

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      osx_image: xcode9

script:
  # brew sometimes fails on something even after a successful python installation
  # we don't want the build to fail
  - ./scripts/travis-setup-osx-python.sh || true
  - sudo python3 -m pip install Cython==0.29 --install-option="--no-cython-compile"
  - sudo python3 -m pip install pytest
  - ./contrib/setup-smt-switch.sh --with-msat --auto-yes --python
  - ./contrib/setup-btor2tools.sh
  - ./configure.sh --with-msat --python --debug
  - cd build && make -j2 && make test && cd ../
  - bash -c "PYTHONPATH=$PYTHONPATH:./build/python:./deps/smt-switch/local/lib/ LD_LIBRARY_PATH=$LD_LIBRARY_PATH/deps/smt-switch/local/lib pytest ./tests"
